apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: dev-

replicas:
  - name: user-service
    count: 1
  - name: product-service
    count: 1
  - name: cart-service
    count: 1
  - name: order-service
    count: 1
  - name: payment-service
    count: 1
  - name: store-service
    count: 1
  - name: api-gateway
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: ecommerce-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: "development"
      - op: replace
        path: /data/DEBUG
        value: "true"
      - op: replace
        path: /data/LOG_LEVEL
        value: "DEBUG"

  - target:
      kind: Deployment
      name: postgres
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"

  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "5Gi"
