apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: nano-ecommerce
data:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/ecommerce"
  REDIS_URL: "redis://redis:6379"
  USER_SERVICE_URL: "user-service:50051"
  PRODUCT_SERVICE_URL: "product-service:50052"
  CART_SERVICE_URL: "cart-service:50053"
  ORDER_SERVICE_URL: "order-service:50054"
  PAYMENT_SERVICE_URL: "payment-service:50055"
  STORE_SERVICE_URL: "store-service:50056"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: nano-ecommerce
type: Opaque
data:
  # Base64 encoded secrets
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  STRIPE_SECRET_KEY: c2tfdGVzdF9FeGFtcGxlS2V5  # sk_test_ExampleKey
  JWT_SECRET: anRfc2VjcmV0X2tleQ==  # jwt_secret_key
